version: '3'
services:
  backend:
    build: .
    command: >
      bash -c '
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        python3 manage.py runserver 0.0.0.0:8000'
    ports:
      - 8001:8000
    volumes:
      - .:/home/fill_factory
    