# Generated by Django 3.2.5 on 2022-04-25 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='工場詳細')),
                ('postal_code', models.CharField(default='000-0000', max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('prefecture', models.CharField(blank=True, choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県'), ('-', '-')], max_length=255, null=True, verbose_name='都道府県')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='市町村区')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='番地')),
                ('address3', models.CharField(blank=True, max_length=255, null=True, verbose_name='建物名')),
                ('mail_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('fax_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='FAX')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_factory_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='factory_factory_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '工場',
                'verbose_name_plural': '工場',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='備考・詳細')),
                ('spec_capacity_each_axis_movement_amount_x', models.IntegerField(blank=True, null=True, verbose_name='容量 / 各軸移動量[mm] / X')),
                ('spec_capacity_each_axis_movement_amount_y', models.IntegerField(blank=True, null=True, verbose_name='容量 / 各軸移動量[mm] / Y')),
                ('spec_capacity_each_axis_movement_amount_z', models.IntegerField(blank=True, null=True, verbose_name='容量 / 各軸移動量[mm] / Z')),
                ('spec_capacity_each_axis_movement_amount_w', models.IntegerField(blank=True, null=True, verbose_name='容量 / 各軸移動量[mm] / W')),
                ('spec_capacity_others_effective_width', models.IntegerField(blank=True, null=True, verbose_name='容量 / その他 / 有効門幅[mm]')),
                ('spec_capacity_others_effective_height', models.IntegerField(blank=True, null=True, verbose_name='容量 / その他 / 有効門高さ[mm]')),
                ('spec_capacity_others_distance_from_table_top_to_spindle_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='容量 / その他 / テーブル上面から主軸端面までの距離[mm]')),
                ('spec_capacity_others_distance_from_column_front_to_main_axis', models.CharField(blank=True, max_length=255, null=True, verbose_name='容量 / その他 / コラム前面から主軸中心までの距離[mm]')),
                ('spec_capacity_others_distance_from_pallet_top_to_main_axis', models.CharField(blank=True, max_length=255, null=True, verbose_name='容量 / その他 / パレット上面から主軸中心までの距離[mm]')),
                ('spec_capacity_others_distance_from_spindle_end_from_pallet_top', models.CharField(blank=True, max_length=255, null=True, verbose_name='容量 / その他 / パレット上面から主軸端面[mm]')),
                ('spec_capacity_others_distance_from_pallet_center_to_spindle_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='容量 / その他 / パレット中心線から主軸端面までの距離[mm]')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_machine_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='factory_machine_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '機械',
                'verbose_name_plural': '機械',
            },
        ),
        migrations.CreateModel(
            name='OwnMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('num', models.IntegerField(verbose_name='保有数')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_ownmachine_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('factory', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='工場')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='factory_ownmachine_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('machine', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='factory.machine', verbose_name='機械')),
            ],
            options={
                'verbose_name': '保有機械',
                'verbose_name_plural': '保有機械',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名前')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_maker_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='factory_maker_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名前')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_machinetype_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='factory_machinetype_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '機械種別',
                'verbose_name_plural': '機械種別',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='factory.machinetype', verbose_name='機械種別'),
        ),
        migrations.AddField(
            model_name='machine',
            name='maker',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='factory.maker', verbose_name='メーカー'),
        ),
        migrations.AddField(
            model_name='factory',
            name='own_machines',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, through='factory.OwnMachine', to='factory.Machine', verbose_name='保有機械'),
        ),
    ]
