# Generated by Django 3.2.5 on 2022-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='会社HP'),
        ),
    ]
