# Generated by Django 3.2.5 on 2022-04-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_each_axis_movement_amount_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/各軸移動量[mm]/W'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_each_axis_movement_amount_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/各軸移動量[mm]/X'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_each_axis_movement_amount_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/各軸移動量[mm]/Y'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_each_axis_movement_amount_z',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/各軸移動量[mm]/Z'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_distance_from_column_front_to_main_axis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='容量/その他/コラム前面から主軸中心までの距離[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_distance_from_pallet_center_to_spindle_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='容量/その他/パレット中心線から主軸端面までの距離[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_distance_from_pallet_top_to_main_axis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='容量/その他/パレット上面から主軸中心までの距離[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_distance_from_spindle_end_from_pallet_top',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='容量/その他/パレット上面から主軸端面[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_distance_from_table_top_to_spindle_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='容量/その他/テーブル上面から主軸端面までの距離[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_effective_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/その他/有効門高さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_capacity_others_effective_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='容量/その他/有効門幅[mm]'),
        ),
    ]
