# Generated by Django 3.2.5 on 2022-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_factory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spec_table_left_and_right_fast_forward_speed_50_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/左右早送り速度[mm/min]/50Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_left_and_right_fast_forward_speed_60_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/左右早送り速度[mm/min]/60Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_left_and_right_feed_speed_50_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/左右送り速度[mm/min]/50Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_left_and_right_feed_speed_60_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/左右送り速度[mm/min]/60Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_travel_distance_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大移動距離[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_travel_distance_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大移動距離[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_travel_distance_up_and_down',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大移動距離[mm]/上下'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_work_dimension_beside',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大ワーク寸法[mm]/横'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_work_dimension_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大ワーク寸法[mm]/高さ'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_maximum_work_dimension_vertical',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/最大ワーク寸法[mm]/縦'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_others_bevel_from_floor_to_table_work_surface',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/その他/床面からテーブル作業面までの高さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_others_table_maximum_loading_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/その他/テーブル最大積載量[kg]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_subtable_dimensions_horizontal',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/サブテーブル寸法/横[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_subtable_dimensions_vertical',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/サブテーブル寸法/縦[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_table_dimension_beside',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/テーブル寸法[mm]/横'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_table_dimension_vertical',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/テーブル寸法[mm]/縦'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_upper_and_lower_fast_feed_speed_50_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/上下早送り速度[mm/min]/50Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_upper_and_lower_fast_feed_speed_60_hz',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/上下早送り速度[mm/min]/60Hz'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_shape_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の形状/高さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_shape_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の形状/間隔[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_shape_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の形状/本数'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_shape_t_groove_mark_dimension',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の形状/T溝呼び寸法'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_shape_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の形状/幅[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_size_beside',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の大きさ[mm]/横'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_table_work_surface_size_vertical',
            field=models.IntegerField(blank=True, null=True, verbose_name='テーブル/作業面の大きさ[mm]/縦'),
        ),
        migrations.AlterField(
            model_name='ownmachine',
            name='num',
            field=models.IntegerField(default=1, help_text='不明な場合は1台とする', verbose_name='保有数'),
        ),
    ]
