# Generated by Django 3.2.5 on 2021-07-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20210721_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'layer': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='factory.factorycategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='materials',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='factory.Material', verbose_name='材質'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='owned_by',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='保有工場'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='processes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='factory.AvailableProcess', verbose_name='対応加工'),
        ),
    ]
