# Generated by Django 3.2.5 on 2022-05-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_factory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownmachine',
            name='num',
            field=models.IntegerField(default=1, help_text='不明な場合は1台とする', verbose_name='保有数'),
        ),
    ]
