# Generated by Django 3.2.5 on 2021-07-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20210721_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorycategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='factory.factorycategory', verbose_name='親カテゴリ'),
        ),
    ]
