# Generated by Django 3.2.5 on 2022-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_auto_20220531_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_basic_bolt_position_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/基礎ボルト位置[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_basic_bolt_position_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/基礎ボルト位置[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_bed_pitfall_size_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/ベッド落とし穴寸法[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_bed_pitfall_size_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/ベッド落とし穴寸法[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_bolster_dimensions_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/ボルスター寸法[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_bolster_dimensions_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/ボルスター寸法[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_electrode_chip_shape_beneath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/電極チップ形状/下部'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_electrode_chip_shape_upper_part',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/電極チップ形状/上部'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_hemed_area_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/裾付面積[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_hemed_area_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/裾付面積[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_maximum_dimensions_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/最大寸法[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_maximum_dimensions_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/最大寸法[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_number_of_strokes_fixed',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/ストローク数[min^-1]/固定'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_number_of_strokes_variable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/ストローク数[min^-1]/可変'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_ability_occurrence_position',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/能力発生位置(下死点上)[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_air_pressure_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/使用空気圧力[kgf/cm^2]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_allowable_usage_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/許容使用率[%]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_back_gauge_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/バックゲージ測長[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_bending_length',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/曲げ長さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_blade_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/刃の長さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_blade_stand_indexing_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/刃物台割出し時間[sec/インデックス]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_chip_dress_function',
            field=models.BooleanField(default=False, verbose_name='刃物台/その他/チップドレス機能'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_claotorial_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/刃物台の形式'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_cooling_water_connection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/冷却水接続'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_cutting_ability',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/切断能力[mm×t]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_cutting_plate_thickness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/切断板厚[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_die_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/ダイハイト[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_display',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/表示[inch]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_down_speed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/下降速度[mm/sec.]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_electrode_chip_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/電極チップホルダー[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_electrode_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/電極径×テーパー[mm×テーパー]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_electrode_horn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/電極ホーン[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_electrode_weld_stroke',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/電極ストローク/溶接ストローク[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_folding_speed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/折り曲げ速度[mm/sec.]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_frame_gap',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/フレームギャップ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_frame_inner_dimension',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/フレーム内側寸法[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_future_adjustment_mechanism',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/ふところ調整機構'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_gap_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/ギャップ深さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_hit_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/ヒットレート[min^-1]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_inner_diameter_tool_shank_diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/内径工具シャンク径[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_intermittent_num_of_strokes_per_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/許容断続毎分ストローク数[min^-1'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_laser_z_axis_movement_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/レーザーZ軸移動量[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_machine_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/機械重量[ton]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_main_electric_machine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/主電動機[kW×P]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_main_motor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/メインモーター[kW]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_maximum_processing_plate_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/最大加工板厚[t]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_motor_for_back_gauge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/バックゲージ用モーター[W]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_number_of_control_axes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/制御軸数'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_number_of_cylinders',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/シリンダ数'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_number_of_processes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/工程数'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_open_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/オープンバック[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_open_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/オープンハイト[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_opening_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/開き速度[mm/s]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_oscillator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/発振器'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_outer_diameter_byte_shank_dimension',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/外径バイトシャンク寸法[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_overlan_monitoring_device_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/オーバーラン監視装置の設定位置(度)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_pressurable_ability',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/加圧能力[kN]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_pressure_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/加圧能力[tf]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_primary_side_power_supply',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/1次側電源'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_processing_range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/加工範囲[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_quenching_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/急閉じ速度[mm/s]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_rated_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/定格容量[kVA]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_repeat_positioning_accuracy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/繰り返し位置決め精度[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_rising_speed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/上昇速度[mm/sec.]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_shear_angle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/シャー角'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_shut_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/シャットハイト[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_slide_adjustment_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/スライド調整長さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_standard_ffg_summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/標準ふところ寸法[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_stroke_length',
            field=models.FloatField(blank=True, null=True, verbose_name='刃物台/その他/ストローク長さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_tank_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/タンク容量[L]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_thickness',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/厚さ'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_tool_mounting_number_of_tool_mounting',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/刃物台の工具取付本数[本]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_top_mass',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/上型質量[kg]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_total_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/総高さ[mm]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_turret_station',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/タレットステーション'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_welding',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/溶接[kVA]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_welding_current',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/溶接電流[A]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_wiring_cable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='刃物台/その他/配線ケーブル'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_others_z_axial_feed_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/その他/Z軸早送り速度[m/min]'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_slide_dimension_front_and_back',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/スライド寸法[mm]/前後'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_slide_dimension_left_and_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/スライド寸法[mm]/左右'),
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_knife_stand_stop_time_quenching_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='刃物台/停止時間/急停止時間[ms]'),
        ),
    ]
