# Generated by Django 3.2.5 on 2021-08-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_factorycategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorycategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'layer__in': (1, 2)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='factory.factorycategory', verbose_name='親カテゴリ'),
        ),
    ]
